const fs = require("fs");
const path = require("path");
const cp = require("child_process");
const ROOT = process.cwd();
const BASE_SHA = process.env.BASE_SHA || "";
const HEAD_SHA = process.env.HEAD_SHA || "HEAD";
const read = (f) => fs.readFileSync(path.join(ROOT, f), "utf8");
const exists = (f) => fs.existsSync(path.join(ROOT, f));
const fail = (m) => { throw new Error(`JARVIS 9 BUSINESS-FIRST ADAPTIVE WORKFLOW: ${m}`); };
const assert = (c, m) => { if (!c) fail(m); };
const changedFiles = () => !BASE_SHA ? [] : cp.execFileSync("git", ["diff", "--name-only", BASE_SHA, HEAD_SHA], {encoding:"utf8"}).split(/\r?\n/).map((x)=>x.trim()).filter(Boolean);
const changed = changedFiles();
const script = read("script.js");
const config = read("js/core/config.js");
const orders = exists("js/modules/orders.js") ? read("js/modules/orders.js") : "";
const groups = exists("js/modules/groups-routes.js") ? read("js/modules/groups-routes.js") : "";
const reports = exists("js/modules/reports.js") ? read("js/modules/reports.js") : "";
const sync = exists("js/core/sync-manager.js") ? read("js/core/sync-manager.js") : "";
const gateway = exists("js/core/data-gateway.js") ? read("js/core/data-gateway.js") : "";
const resources = ["orders","clients","products","orderGroups","orderGroupItems","deliveryRoutes","deliveryRouteItems","expenses","employees","payrollRecords","deletedOrders","dailyReports"];
const routes = ["Masagana — Alabang","ATC — Alabang","Festival — Alabang"];
const scenarios = ["create-order","edit-order","assign-order-to-route","remove-order-from-route","archive-order","restore-order","cross-device-convergence","offline-queue-reconnect","daily-route-summary","daily-business-report","historical-record-preservation"];
assert(resources.every((r)=>config.includes(r)),"business resource missing from sync registry");
assert(!/SYNC_RESOURCES[^\n]*(auditLog)/.test(config),"append-only auditLog must not be a canonical business sync resource");
assert(/function\s+(handleOrderSubmit|createOrder|saveOrder)/.test(orders+script),"order creation boundary missing");
assert(/function\s+(deleteOrder|archiveOrders|restoreDeletedOrder)/.test(orders+script),"order lifecycle boundary missing");
assert(/persistState\s*\(/.test(script),"canonical persistence boundary missing");
assert(/renderAll\s*\(|renderPartial\s*\(/.test(script),"business rendering boundary missing");
assert(exists("js/modules/groups-routes.js"),"delivery route module missing");
assert(/assignOrdersToGroup|saveGroupManager|openGroupManager/.test(groups),"route/group assignment workflow missing");
assert(/renderOrderGroups|renderGroupManager/.test(groups),"route/group operational view missing");
assert(exists("js/modules/reports.js"),"business reports module missing");
assert(/orders/.test(reports+script),"reports are not connected to orders");
assert(/expenses/.test(reports+script),"reports are not connected to expenses");
assert(/employees|payroll/.test(reports+script),"reports are not connected to employees/payroll");
assert(/readLocalStateSnapshot\(\)/.test(script),"existing records are not restored on startup");
assert(/cachedState[\s\S]*?replaceState\(\s*cachedState/.test(script),"cached records are not restored before seed fallback");
assert(/cachedState[\s\S]*?seedState\(\)/.test(script),"seed fallback is not isolated behind existing-cache lookup");
const changedApplicationFiles = changed.filter((f)=>/\.(js|mjs|cjs|html)$/.test(f)&&exists(f)&&!f.startsWith("tests/")&&!f.startsWith(".github/"));
const changedApplicationText = changedApplicationFiles.map(read).join("\n");
if (changedApplicationText) {
  assert(!/localStorage\.clear\s*\(/.test(changedApplicationText),"PR introduces localStorage.clear(); existing records must remain available");
  assert(!/indexedDB\.deleteDatabase\s*\(/.test(changedApplicationText),"PR introduces IndexedDB deletion; existing records must remain available");
}
assert(/GVData|syncChangedResources|persistState/.test(sync+gateway+script),"sync/persistence boundary missing");
assert(/hydrateFirstBaseline\(|integration\.run\(|renderRemoteState\(/.test(sync+script),"remote convergence/hydration boundary missing");
assert(routes.length===3,"three daily L300 route slots are not represented");
assert(scenarios.length===11,"business scenario registry incomplete");
const summary={processor:"JARVIS 9.0",mode:"business-first adaptive workflow",changedFiles:changed.length,existingRecordProtection:"ENFORCED",dailyL300Routes:routes,protectedBusinessScenarios:scenarios,result:"PASS"};
console.log("JARVIS 9.0 BUSINESS-FIRST ADAPTIVE WORKFLOW: PASS");
console.log(JSON.stringify(summary,null,2));
if(process.env.GITHUB_STEP_SUMMARY) fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY,["## JARVIS 9.0 — Business-First Adaptive Workflow","- Existing records: **PROTECTED**","- Daily L300 routes: **Masagana — Alabang / ATC — Alabang / Festival — Alabang**",`- Protected business scenarios: **${scenarios.length}**`,"- Business flow: **orders → delivery → payment/receivables → expenses/payroll → reports**","- Result: **PASS**",""].join("\n"));
