const fs = require("node:fs");
const assert = require("node:assert/strict");
const app = fs.readFileSync("script.js", "utf8");
const gateway = fs.readFileSync("js/core/data-gateway.js", "utf8");
const resources = ["orders","payments","expenses","payroll_records","order_groups","delivery_routes","daily_reports","deleted_orders","order_group_items","delivery_route_items","audit_logs"];
for (const resource of resources) assert.match(gateway,new RegExp(`case \\\"${resource}\\\"\\s*:`),`Missing gateway adapter for ${resource}`);
assert.match(gateway,/requireAuthenticatedManager\(/);
assert.match(gateway,/function sync\(\)/);
assert.match(gateway,/toSupabaseOrder\(/);
assert.match(gateway,/fromSupabaseOrder\(/);
assert.match(gateway,/company_id/);
assert.match(gateway,/legacy_id/);
assert.match(app,/function cloudSyncAdapterReady\(\)\s*\{\s*return false;/);
console.log("Sprint 19 transaction-sync activation readiness: PASS");
